# Generated by Django 3.0 on 2020-01-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0003_carrinho_senha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrinho',
            options={'verbose_name_plural': 'Carrinho'},
        ),
        migrations.AlterModelOptions(
            name='suporte',
            options={'verbose_name_plural': 'Suporte'},
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='senha',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='suporte',
            name='texto',
            field=models.TextField(max_length=700),
        ),
    ]
